[options]
admin_passwd = Pr0t3ct10n!

db_host = False
db_port = 5432
db_name = odoo_db_main
db_user = odoo
db_password = Pr0t3ct10n!
list_db = true

# FOLDERS
# addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
# data_dir = /var/lib/odoo
addons_path = C:/OdooPipeline/odoo/addons
data_dir = C:/OdooPipeline/odoo/data_dir

# Proxy
xmlrpc_port = 8069
